#!/usr/bin/env bun
/**
 * Deterministic documentation generator.
 *
 * Regenerates the auto-managed regions of the docs site from the plugin's
 * actual components, so the reference pages can never silently drift. Replaces
 * the old manual `/release-docs` skill.
 *
 *   bun run docs:build   # rewrite the generated regions in place
 *   bun run docs:check   # exit non-zero if any committed file is out of date (CI)
 *
 * Per reference page it owns two things:
 *   1. the component card sections (between `<!-- GENERATED:<id> START/END -->`)
 *   2. the sidebar "On This Page" list (the <ul> after that heading)
 * Plus the four stat numbers on the landing page. All other page chrome
 * (nav, header, intros, footer) is preserved verbatim.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "fs"
import path from "path"
import { parseFrontmatter } from "../src/utils/frontmatter"

const ROOT = path.resolve(import.meta.dir, "..")
const PLUGIN = path.join(ROOT, "plugins/agentic-engineering")
const DOCS = path.join(ROOT, "docs")

export type Component = { name: string; description: string; category: string }
type NavItem = { href: string; label: string }

// ---- collection ------------------------------------------------------------

function fm(file: string): { name: string; description: string } {
  const { data } = parseFrontmatter(readFileSync(file, "utf8"))
  return { name: String(data.name ?? ""), description: String(data.description ?? "").trim() }
}

function mdIn(dir: string): string[] {
  if (!existsSync(dir)) return []
  return readdirSync(dir).filter((n) => n.endsWith(".md")).map((n) => path.join(dir, n)).sort()
}

export function collectAgents(): Component[] {
  const dir = path.join(PLUGIN, "agents")
  const cats = readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name)
  const out: Component[] = []
  for (const cat of cats) for (const f of mdIn(path.join(dir, cat))) out.push({ ...fm(f), category: cat })
  return out
}

export function collectCommands(): Component[] {
  const out: Component[] = []
  for (const f of mdIn(path.join(PLUGIN, "commands", "workflows"))) out.push({ ...fm(f), category: "workflow" })
  for (const f of mdIn(path.join(PLUGIN, "commands"))) out.push({ ...fm(f), category: "utility" })
  return out
}

export function collectSkills(): Component[] {
  const dir = path.join(PLUGIN, "skills")
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(path.join(dir, e.name, "SKILL.md")))
    .map((e) => ({ name: e.name, description: fm(path.join(dir, e.name, "SKILL.md")).description, category: "skill" }))
    .sort((a, b) => a.name.localeCompare(b.name))
}

export function collectMcp(): Component[] {
  const pj = JSON.parse(readFileSync(path.join(PLUGIN, ".claude-plugin/plugin.json"), "utf8"))
  return Object.entries(pj.mcpServers ?? {}).map(([name, cfg]: [string, any]) => ({
    name,
    description: String(cfg.url ?? cfg.type ?? ""),
    category: String(cfg.type ?? "http"),
  }))
}

// ---- html helpers ----------------------------------------------------------

export function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

/** Replace the inner content of a marker pair, or splice in on first run. */
function spliceContent(html: string, id: string, beginAnchor: string, endAnchor: string, inner: string): string {
  const startMark = `<!-- GENERATED:${id} START`
  const endMark = `<!-- GENERATED:${id} END -->`
  if (html.includes(startMark)) {
    const s = html.indexOf(startMark)
    const ls = html.lastIndexOf("\n", s) + 1
    const indent = html.slice(ls, s)
    const e = html.indexOf(endMark)
    const eolEnd = html.indexOf("\n", e)
    return html.slice(0, ls) + wrap(indent, id, inner) + html.slice(eolEnd === -1 ? html.length : eolEnd)
  }
  const b = html.indexOf(beginAnchor)
  if (b === -1) throw new Error(`generate-docs: begin anchor not found for "${id}": ${beginAnchor}`)
  const ls = html.lastIndexOf("\n", b) + 1
  const indent = html.slice(ls, b)
  const eAnchor = html.indexOf(endAnchor, b)
  if (eAnchor === -1) throw new Error(`generate-docs: end anchor not found for "${id}": ${endAnchor}`)
  const eLine = html.lastIndexOf("\n", eAnchor) + 1
  return html.slice(0, ls) + wrap(indent, id, inner) + "\n" + html.slice(eLine)
}

function wrap(indent: string, id: string, inner: string): string {
  return (
    `${indent}<!-- GENERATED:${id} START — auto-generated by scripts/generate-docs.ts (run: bun run docs:build); do not edit by hand -->\n` +
    `${inner}\n` +
    `${indent}<!-- GENERATED:${id} END -->`
  )
}

/** Rewrite the <ul> that follows the "On This Page" sidebar heading. Idempotent. */
function replaceOnThisPage(html: string, items: NavItem[]): string {
  const h = html.indexOf("On This Page")
  if (h === -1) return html
  const ulStart = html.indexOf("<ul>", h)
  const ulEnd = html.indexOf("</ul>", ulStart)
  if (ulStart === -1 || ulEnd === -1) return html
  const lineStart = html.lastIndexOf("\n", ulStart) + 1
  const indent = html.slice(lineStart, ulStart)
  const liIndent = indent + "  "
  const lis = items.map((it) => `${liIndent}<li><a href="${it.href}">${esc(it.label)}</a></li>`).join("\n")
  return html.slice(0, ulStart) + `<ul>\n${lis}\n${indent}</ul>` + html.slice(ulEnd + "</ul>".length)
}

// ---- card / section renderers ----------------------------------------------

function section(id: string, icon: string, heading: string, count: number, cards: string[]): string {
  return (
    `        <section id="${id}">\n` +
    `          <h2><i class="fa-solid ${icon}"></i> ${heading} (${count})</h2>\n` +
    `${cards.join("\n")}\n` +
    `        </section>`
  )
}

function card(kind: string, id: string, header: string, description: string, invocation: string): string {
  return (
    `          <div class="${kind}-detail" id="${id}">\n` +
    `            <div class="${kind}-detail-header">\n` +
    `${header}\n` +
    `            </div>\n` +
    `            <p class="${kind}-detail-description">${esc(description)}</p>\n` +
    `            <div class="card-code-block">\n` +
    `              <pre><code>${esc(invocation)}</code></pre>\n` +
    `            </div>\n` +
    `          </div>`
  )
}

const AGENT_CATS = [
  { key: "review", nav: "Review", heading: "Review Agents", icon: "fa-code-pull-request" },
  { key: "research", nav: "Research", heading: "Research Agents", icon: "fa-magnifying-glass" },
  { key: "workflow", nav: "Workflow", heading: "Workflow Agents", icon: "fa-arrows-spin" },
  { key: "design", nav: "Design", heading: "Design Agents", icon: "fa-palette" },
  { key: "docs", nav: "Docs", heading: "Docs Agents", icon: "fa-book" },
]

function buildAgents(agents: Component[]): { inner: string; nav: NavItem[] } {
  const sections: string[] = []
  const nav: NavItem[] = []
  const cats = [...AGENT_CATS.map((c) => c.key), ...new Set(agents.map((a) => a.category))].filter((c, i, arr) => arr.indexOf(c) === i)
  for (const key of cats) {
    const items = agents.filter((a) => a.category === key)
    if (!items.length) continue
    const meta = AGENT_CATS.find((c) => c.key === key) ?? { key, nav: key, heading: `${key} Agents`, icon: "fa-cube" }
    const id = `${key}-agents`
    const cards = items.map((a) =>
      card(
        "agent",
        a.name,
        `              <h3>${esc(a.name)}</h3>\n              <span class="agent-badge">${esc(meta.nav)}</span>`,
        a.description,
        `claude agent ${a.name} "..."`,
      ),
    )
    sections.push(section(id, meta.icon, meta.heading, items.length, cards))
    nav.push({ href: `#${id}`, label: `${meta.nav} (${items.length})` })
  }
  return { inner: sections.join("\n\n"), nav }
}

const COMMAND_GROUPS = [
  { key: "workflow", id: "workflow-commands", nav: "Workflow", heading: "Workflow Commands", icon: "fa-arrows-spin" },
  { key: "utility", id: "utility-commands", nav: "Utility", heading: "Utility Commands", icon: "fa-screwdriver-wrench" },
]

function buildCommands(commands: Component[]): { inner: string; nav: NavItem[] } {
  const sections: string[] = []
  const nav: NavItem[] = []
  for (const g of COMMAND_GROUPS) {
    const items = commands.filter((c) => c.category === g.key)
    if (!items.length) continue
    const cards = items.map((c) =>
      card(
        "command",
        slug(c.name),
        `              <code class="command-detail-name">/${esc(c.name)}</code>`,
        c.description,
        `/${c.name}`,
      ),
    )
    sections.push(section(g.id, g.icon, g.heading, items.length, cards))
    nav.push({ href: `#${g.id}`, label: `${g.nav} (${items.length})` })
  }
  return { inner: sections.join("\n\n"), nav }
}

function buildSkills(skills: Component[]): { inner: string; nav: NavItem[] } {
  const cards = skills.map((s) =>
    card("skill", s.name, `              <h3>${esc(s.name)}</h3>`, s.description, `skill: ${s.name}`),
  )
  const inner = section("all-skills", "fa-wand-magic-sparkles", "Skills", skills.length, cards)
  return { inner, nav: [{ href: "#all-skills", label: `Skills (${skills.length})` }] }
}

function buildMcp(mcp: Component[]): { inner: string; nav: NavItem[] } {
  const sections: string[] = []
  const nav: NavItem[] = []
  for (const s of mcp) {
    const id = slug(s.name)
    sections.push(
      `        <section id="${id}">\n` +
        `          <h2><i class="fa-solid fa-server"></i> ${esc(s.name)}</h2>\n` +
        `          <p class="mcp-detail-description">Type: <code>${esc(s.category)}</code>${s.description ? ` · <code>${esc(s.description)}</code>` : ""}</p>\n` +
        `        </section>`,
    )
    nav.push({ href: `#${id}`, label: esc(s.name) })
  }
  return { inner: sections.join("\n\n"), nav }
}

// ---- landing-page stats ----------------------------------------------------

export function applyIndexStats(html: string, counts: number[]): string {
  let i = 0
  return html.replace(/(<div class="stat-number">)\d+(<\/div>)/g, (m, a, b) => (i < counts.length ? `${a}${counts[i++]}${b}` : m))
}

// ---- driver ----------------------------------------------------------------

type FileUpdate = { file: string; next: string }

export function buildUpdates(): FileUpdate[] {
  const agents = collectAgents()
  const commands = collectCommands()
  const skills = collectSkills()
  const mcp = collectMcp()

  const read = (rel: string) => readFileSync(path.join(DOCS, rel), "utf8")
  const updates: FileUpdate[] = []

  const pages: Array<{ file: string; id: string; begin: string; end: string; built: { inner: string; nav: NavItem[] } }> = [
    { file: "pages/agents.html", id: "agents", begin: "<!-- Review Agents -->", end: "<!-- Navigation -->", built: buildAgents(agents) },
    { file: "pages/commands.html", id: "commands", begin: "<!-- Workflow Commands -->", end: "<!-- Navigation -->", built: buildCommands(commands) },
    { file: "pages/skills.html", id: "skills", begin: "<!-- Development Tools -->", end: "<!-- Navigation -->", built: buildSkills(skills) },
    { file: "pages/mcp-servers.html", id: "mcp", begin: "<!-- Playwright -->", end: "<!-- Manual Configuration -->", built: buildMcp(mcp) },
  ]

  for (const p of pages) {
    let html = read(p.file)
    html = spliceContent(html, p.id, p.begin, p.end, p.built.inner)
    html = replaceOnThisPage(html, p.built.nav)
    updates.push({ file: path.join(DOCS, p.file), next: html })
  }

  const counts = [agents.length, commands.length, skills.length, mcp.length]
  updates.push({ file: path.join(DOCS, "index.html"), next: applyIndexStats(read("index.html"), counts) })

  return updates
}

function main() {
  const check = process.argv.includes("--check")
  const stale: string[] = []
  for (const { file, next } of buildUpdates()) {
    if (readFileSync(file, "utf8") === next) continue
    stale.push(path.relative(ROOT, file))
    if (!check) writeFileSync(file, next)
  }
  if (check && stale.length) {
    console.error(`Docs out of date — run \`bun run docs:build\`:\n  ${stale.join("\n  ")}`)
    process.exit(1)
  }
  console.log(check ? "Docs up to date." : stale.length ? `Rebuilt: ${stale.join(", ")}` : "Docs already current.")
}

if (import.meta.main) main()
